define({
	"Title": "エディタ",
	"MBFile": "ファイル",
	"MBNewProj": "新しいプロジェクト",
	"MBLoadProj": "ロードプロジェクト",
	"MBSave": "保存",
	"MBSaveAs": "名前を付けて保存...",
	"MBExport": "輸出",
	"MBExportCGEN": ".cgen",
	"MBExportXML": ".xml",
	"MBExportJSON": ".json",
	"MBQuit": "やめる",

	"MBEdit": "編集",
	"MBCreate": "作る",
	"MBEmptyObj": "空のオブジェクト",
	"MBKeyItem": "重要品目",
	"MBConsumable": "消耗品",
	"MBArmor": "鎧",
	"MBWeapon": "武器",

	"MBHelp": "助けて",
	"MBAbout": "約",
	"MBSearchInputPH": "検索：名前または識別",


	"Components": "コンポーネント",
	"ErrorsTitle": "エラー：",
	"WarningsTitle": "警告：",

	"GeneralTab": "一般的な",
	"IDTitle": "識別",
	"IDInput": "識別",
	"IDInputPH": "固有の識別",
	"NameInput": "名前",
	"NameInputPH": "一意の名前",
	"DescriptionInput": "説明",
	"DescInputPH": "詳細な説明",
	"ConnectionsTitle": "接続",
	"CreateConnection": "新しい接続を作成します。",
	"ConnectUndefined": "選択...",
	"ConnectRequires": "が必要です",
	"ConnectConsumes": "消費する",
	"TargetSelectBtn": "クリックして選択します",

	"RenderableTab": "レンダリングできる",
	"IconsTitle": "アイコン",
	"SmallIconInput": "スモールアイコン (64x64)",
	"SmallIconInputPH": "小さいアイコンのファイル名",
	"MediumIconInput": "ミディアムアイコン (128x128)",
	"MediumIconInputPH": "ミディアムアイコンファイル名",
	"LargeIconInput": "大きいアイコン (256x256)",
	"LargeIconInputPH": "大きいアイコンのファイル名",

	"GeneralTitle": "一般的な",
	"EquipableTab": "装備可能",
	"EquipmentSlotInput": "機器スロット：",
	"SlotUndefined": "選択...",
	"MinLevelInput": "最小レベル：",
	"MaxLevelInput": "最大レベル：",

	"StatsTitle": "統計",

	"TagsTab": "タグ",
	"KeysTitle": "キーズ",
	"ValuesTitle": "値",
	"AddTagBtn": "タグを追加する",
	"TagKeyInputPH": "タグ名",
	"TagValueInputPH": "タグ値",

	"Dagger": "短剣",
	"Sword": "剣",
	"GreatSword": "グレートソード",
	"Fists": "拳",
	"Bow": "弓矢",
	"Wand": "ワンド",
	"Staff": "スタッフ",
	"Dolls": "ドールズ",
	"Head": "ヘッド",
	"EaringLeft": "左イヤリング",
	"EaringRight": "右のイヤリング",
	"Neck": "ネック",
	"Shoulders": "肩",
	"Body": "ボディ",
	"Hands": "ハンズ",
	"RingLeft": "左リング",
	"RingRight": "右のリング",
	"Belt": "ベルト",
	"Legs": "脚",
	"Shoes": "靴",

	"HP-abbr": "HP",
	"HP-full": "健康",
	"MP-abbr": "MP",
	"MP-full": "マジック",
	"SP-abbr": "SP",
	"SP-full": "精神",
	"STR-abbr": "STR",
	"STR-full": "ストレングス",
	"DEX-abbr": "DEX",
	"DEX-full": "器用さ",
	"VIT-abbr": "VIT",
	"VIT-full": "活力",
	"CON-abbr": "CON",
	"CON-full": "憲法",
	"EVA-abbr": "EVA",
	"EVA-full": "回避",
	"WIS-abbr": "WIS",
	"WIS-full": "知恵",
	"INT-abbr": "INT",
	"INT-full": "インテリジェンス",
	"MND-abbr": "MND",
	"MND-full": "心",
	"TRQ-abbr": "TRQ",
	"TRQ-full": "静かな",
	"BKR-abbr": "BKR",
	"BKR-full": "ブードゥー教",

	"MMTitle": "メインメニュー",
	"MMEditorBtn": "エディタ",
	"MMSimulatorBtn": "シミュレータ",
	"MMTestPlayerBtn": "テストプレイヤー",
	"MMProjectViewerBtn": "プロジェクトビューア",
	"MMComponentEditorBtn": "コンポーネントエディタ"
});