define({
	"About": "バイ Dan Cuccia",
	"OK": "はい",
	"Yes": "はい",
	"No": "ノー",
	"Cancel": "キャンセル",
	"AreYouSure": "本気ですか？",
	"SaveCurrent": "現在の変更を保存しますか？",
	"SaveError": "エラーは、保存するすべてのエラーについて、内容を確認し、再度お試しくださいしようとして発生しました。",
	"EquipSlotUndefined": "機器のスロットが割り当てられている必要があります",
	"ConnectConditionUndefined": "接続条件を定義する必要があります",
	"ConnectZeroQuantity": "意味がないゼロの数量要件",
	"ConnectMaxQuantity": "数量要件は1000未満でなければなりません",
	"ConnectTargetUndefined": "接続対象が定義されていない",
	"IDUndefined": "識別は、定義する必要があります",
	"DuplicateID": "重複の識別が見つかりました。",
	"DuplicateName": "名前が見つかった重複",
	"NameUndefined": "名前を定義する必要があります",
	"DescriptionUndefined": "説明は定義されていません",
	"SmallIconUndefined": "小さいアイコンファイルが定義されていません",
	"MediumIconUndefined": "ミディアムアイコンファイルは定義されていません",
	"LargeIconUndefined": "大きいアイコンファイルが定義されていません",
	"TagKeyUndefined": "タグは、キーが定義されている必要があります",
	"TagValueUndefined": "タグは、値が定義されている必要があります",
	"TagKeyDuplicate": "重複キーが見つかりました。"
});