define({
	"Title": "编辑",
	"MBFile": "文件",
	"MBNewProj": "新建项目",
	"MBLoadProj": "加载项目",
	"MBSave": "保存",
	"MBSaveAs": "另存为...",
	"MBExport": "出口",
	"MBExportCGEN": ".cgen",
	"MBExportXML": ".xml",
	"MBExportJSON": ".json",
	"MBQuit": "退出",

	"MBEdit": "编辑",
	"MBCreate": "创建",
	"MBEmptyObj": "空对象",
	"MBKeyItem": "重点项目",
	"MBConsumable": "耗材",
	"MBArmor": "装甲",
	"MBWeapon": "武器",

	"MBHelp": "帮助",
	"MBAbout": "关于",
	"MBSearchInputPH": "搜索：产品名称或标识",


	"Components": "组件",
	"ErrorsTitle": "错误：",
	"WarningsTitle": "警告：",

	"GeneralTab": "通用",
	"IDTitle": "鉴定",
	"IDInput": "鉴定",
	"IDInputPH": "唯一标识",
	"NameInput": "名字",
	"NameInputPH": "独特的名称",
	"DescriptionInput": "描述",
	"DescInputPH": "详细说明",
	"ConnectionsTitle": "连接",
	"CreateConnection": "创建一个新的连接",
	"ConnectUndefined": "选择...",
	"ConnectRequires": "要求",
	"ConnectConsumes": "消耗",
	"TargetSelectBtn": "单击以选中",

	"RenderableTab": "渲染",
	"IconsTitle": "图标",
	"SmallIconInput": "小图标 (64x64)",
	"SmallIconInputPH": "小图标文件名",
	"MediumIconInput": "中等图标 (128x128)",
	"MediumIconInputPH": "中等图标文件名",
	"LargeIconInput": "大图标 (256x256)",
	"LargeIconInputPH": "大图标文件名",

	"GeneralTitle": "一般",
	"EquipableTab": "设备",
	"EquipmentSlotInput": "设备插槽:",
	"SlotUndefined": "选择...",
	"MinLevelInput": "最低水平:",
	"MaxLevelInput": "最高级别:",

	"StatsTitle": "统计",

	"TagsTab": "标签",
	"KeysTitle": "钥匙",
	"ValuesTitle": "值",
	"AddTagBtn": "添加标签",
	"TagKeyInputPH": "标签名称",
	"TagValueInputPH": "标签值",

	"Dagger": "匕首",
	"Sword": "剑",
	"GreatSword": "大剑",
	"Fists": "拳头",
	"Bow": "弓箭",
	"Wand": "棍",
	"Staff": "员工",
	"Dolls": "玩偶",
	"Head": "头",
	"EaringLeft": "左耳环",
	"EaringRight": "右耳环",
	"Neck": "颈部",
	"Shoulders": "肩膀",
	"Body": "体",
	"Hands": "手",
	"RingLeft": "左环",
	"RingRight": "右手戒指",
	"Belt": "腰带",
	"Legs": "腿",
	"Shoes": "鞋",

	"HP-abbr": "HP",
	"HP-full": "健康",
	"MP-abbr": "MP",
	"MP-full": "神奇点",
	"SP-abbr": "SP",
	"SP-full": "精神点",
	"STR-abbr": "STR",
	"STR-full": "实力",
	"DEX-abbr": "DEX",
	"DEX-full": "灵巧",
	"VIT-abbr": "VIT",
	"VIT-full": "活力",
	"CON-abbr": "CON",
	"CON-full": "宪法",
	"EVA-abbr": "EVA",
	"EVA-full": "闪避",
	"WIS-abbr": "WIS",
	"WIS-full": "智慧",
	"INT-abbr": "INT",
	"INT-full": "情报",
	"MND-abbr": "MND",
	"MND-full": "心",
	"TRQ-abbr": "TRQ",
	"TRQ-full": "宁静",
	"BKR-abbr": "BKR",
	"BKR-full": "巫毒",

	"MMTitle": "主菜单",
	"MMEditorBtn": "编辑",
	"MMSimulatorBtn": "模拟器",
	"MMTestPlayerBtn": "测试玩家",
	"MMProjectViewerBtn": "项目浏览器",
	"MMComponentEditorBtn": "组件编辑器"
});