define({
	"About": "由 Daniel Cuccia",
	"OK": "行",
	"Yes": "是的",
	"No": "没有",
	"Cancel": "取消",
	"AreYouSure": "你确定吗？",
	"SaveCurrent": "保存当前的变化？",
	"SaveError": "发生错误试图保存，查看您的内容的任何错误，并请重试。",
	"EquipSlotUndefined": "装备槽必须分配",
	"ConnectConditionUndefined": "连接条件必须定义",
	"ConnectZeroQuantity": "零的数量要求没有任何意义",
	"ConnectMaxQuantity": "数量要求必须小于1000",
	"ConnectTargetUndefined": "连接目标尚未定义",
	"IDUndefined": "标识必须被定义",
	"DuplicateID": "重复鉴定发现",
	"DuplicateName": "重名发现",
	"NameUndefined": "名称必须定义",
	"DescriptionUndefined": "描述并不限定",
	"SmallIconUndefined": "小图标文件没有定义",
	"MediumIconUndefined": "中等图标文件没有定义",
	"LargeIconUndefined": "大图标的文件没有定义",
	"TagKeyUndefined": "标签必须有定义键",
	"TagValueUndefined": "标签必须有定义的值",
	"TagKeyDuplicate": "重复键找到"
});