define({
	"Title": "Editor",
	"MBFile": "Berkas",
	"MBNewProj": "Proyek Baru",
	"MBLoadProj": "Beban Proyek",
	"MBSave": "Simpan",
	"MBSaveAs": "Save As...",
	"MBExport": "Ekspor",
	"MBExportCGEN": ".cgen",
	"MBExportXML": ".xml",
	"MBExportJSON": ".json",
	"MBQuit": "Berhenti",

	"MBEdit": "Sunting",
	"MBCreate": "Membuat",
	"MBEmptyObj": "Obyek Kosong",
	"MBKeyItem": "Key Barang",
	"MBConsumable": "Consumable",
	"MBArmor": "Baju Zirah",
	"MBWeapon": "Senjata",

	"MBHelp": "Membantu",
	"MBAbout": "Tentang",
	"MBSearchInputPH": "Pencarian: Nama atau Identifikasi",


	"Components": "Komponen",
	"ErrorsTitle": "Kesalahan:",
	"WarningsTitle": "Peringatan:",

	"GeneralTab": "Umum",
	"IDTitle": "Identifikasi",
	"IDInput": "Identifikasi",
	"IDInputPH": "Identifikasi Unik",
	"NameInput": "Nama",
	"NameInputPH": "Nama Yang Unik",
	"DescriptionInput": "Deskripsi",
	"DescInputPH": "Detil Deskripsi",
	"ConnectionsTitle": "Koneksi",
	"CreateConnection": "Buat koneksi baru",
	"ConnectUndefined": "Pilih...",
	"ConnectRequires": "Membutuhkan",
	"ConnectConsumes": "Mengkonsumsi",
	"TargetSelectBtn": "Klik untuk memilih",

	"RenderableTab": "Memberikan",
	"IconsTitle": "Ikon",
	"SmallIconInput": "Ikon Kecil (64x64)",
	"SmallIconInputPH": "Ikon Kecil Filename",
	"MediumIconInput": "Ikon Menengah (128x128)",
	"MediumIconInputPH": "Ikon Menengah Filename",
	"LargeIconInput": "Ikon Besar (256x256)",
	"LargeIconInputPH": "Ikon Besar Filename",

	"GeneralTitle": "Umum",
	"EquipableTab": "Peralatan",
	"EquipmentSlotInput": "Peralatan Jenis:",
	"SlotUndefined": "Pilih...",
	"MinLevelInput": "Tingkat Minimum:",
	"MaxLevelInput": "Tingkat Maksimum:",

	"StatsTitle": "Statistik",

	"TagsTab": "Tags",
	"KeysTitle": "Kunci-Kunci",
	"ValuesTitle": "Nilai Nilai",
	"AddTagBtn": "Tambahkan Tag",
	"TagKeyInputPH": "Tag-Nama",
	"TagValueInputPH": "Tag-Nilai",

	"Dagger": "Pisau Belati",
	"Sword": "Pedang",
	"GreatSword": "Besar Pedang",
	"Fists": "Kepalan Tangan",
	"Bow": "Busur Panah",
	"Wand": "Tongkat Sihir",
	"Staff": "Staf",
	"Dolls": "Boneka",
	"Head": "Kepala",
	"EaringLeft": "Left Earring",
	"EaringRight": "Right Earring",
	"Neck": "Leher",
	"Shoulders": "Bahu",
	"Body": "Tubuh",
	"Hands": "Tangan",
	"RingLeft": "Left Ring",
	"RingRight": "Tepat Earring",
	"Belt": "Ikat Pinggang",
	"Legs": "Kaki",
	"Shoes": "Sepatu",

	"HP-abbr": "HP",
	"HP-full": "bidang kesehatan",
	"MP-abbr": "MP",
	"MP-full": "sihir",
	"SP-abbr": "SP",
	"SP-full": "semangat",
	"STR-abbr": "STR",
	"STR-full": "kekuatan",
	"DEX-abbr": "DEX",
	"DEX-full": "ketangkasan",
	"VIT-abbr": "VIT",
	"VIT-full": "daya hidup",
	"CON-abbr": "CON",
	"CON-full": "Undang Undang",
	"EVA-abbr": "EVA",
	"EVA-full": "penghindaran",
	"WIS-abbr": "WIS",
	"WIS-full": "kebijaksanaan",
	"INT-abbr": "INT",
	"INT-full": "kecerdasan",
	"MND-abbr": "MND",
	"MND-full": "pikiran",
	"TRQ-abbr": "TRQ",
	"TRQ-full": "tenang",
	"BKR-abbr": "BKR",
	"BKR-full": "guna-guna",

	"MMTitle": "Pilihan utama",
	"MMEditorBtn": "Editor",
	"MMSimulatorBtn": "Menirukan",
	"MMTestPlayerBtn": "Uji Pemain",
	"MMProjectViewerBtn": "Tampilan Proyek"
	"MMComponentEditorBtn": "Editor Komponen"
});