define({
	"About": "oleh Dan Cuccia",
	"OK": "Boleh Saja",
	"Yes": "Iya Nih",
	"No": "Tak Ada",
	"Cancel": "Tidak Jadi",
	"AreYouSure": "Apakah Anda yakin?",
	"SaveCurrent": "Simpan perubahan saat ini ?",
	"SaveError": "Kesalahan telah terjadi mencoba untuk menyimpan, meninjau konten untuk kesalahan, dan coba lagi.",
	"EquipSlotUndefined": "Sepotong peralatan harus ditetapkan",
	"ConnectConditionUndefined": "Jenis peralatan harus ditetapkan",
	"ConnectZeroQuantity": "Kuantitas kebutuhan Nol tidak masuk akal",
	"ConnectMaxQuantity": "Kuantitas persyaratan harus kurang dari 1000",
	"ConnectTargetUndefined": "Koneksi Sasaran belum didefinisikan",
	"IDUndefined": "Identifikasi harus didefinisikan",
	"DuplicateID": "Duplikat identifikasi ditemukan",
	"DuplicateName": "Duplikat Nama ditemukan",
	"NameUndefined": "Nama harus didefinisikan",
	"DescriptionUndefined": "Deskripsi tidak terdefinisi",
	"SmallIconUndefined": "Icon file yang kecil tidak terdefinisi",
	"MediumIconUndefined": "Icon file yang sedang tidak terdefinisi",
	"LargeIconUndefined": "Icon file besar tidak terdefinisi",
	"TagKeyUndefined": "Tag harus kunci didefinisikan",
	"TagValueUndefined": "Tag harus memiliki nilai yang ditetapkan",
	"TagKeyDuplicate": "Duplikat Key ditemukan"
});