define({
	root: {
		Title: "Editor",
		MBFile: "File",
		MBNewProj: "New Project",
		MBLoadProj: "Load Project",
		MBSave: "Save",
		MBSaveAs: "Save As...",
		MBExport: "Export",
		MBExportCGEN: ".cgen",
		MBExportXML: ".xml",
		MBExportJSON: ".json",
		MBQuit: "Quit",

		MBEdit: "Edit",
		MBView: "View",
		MBCreate: "Create",
		MBEmptyObj: "Empty Object",
		MBKeyItem: "Key Item",
		MBConsumable: "Consumable",
		MBArmor: "Armor",
		MBWeapon: "Weapon",

		MBHelp: "Help",
		MBAbout: "About",
		MBSearchInputPH: "Search: Name or ID",


		Components: "Components",
		ErrorsTitle: "Errors:",
		WarningsTitle: "Warnings:",

		GeneralTab: "General",
		IDTitle: "Identification",
		IDInput: "ID",
		IDInputPH: "Unique ID",
		NameInput: "Name",
		NameInputPH: "Unique Name",
		DescriptionInput: "Description",
		DescInputPH: "Detailed Description",
		ConnectionsTitle: "Connections",
		CreateConnection: "Create a new connection",
		ConnectUndefined: "Select...",
		ConnectRequires: "Requires",
		ConnectConsumes: "Consumes",
		TargetSelectBtn: "Click to select",

		RenderableTab: "Renderable",
		IconsTitle: "Icons",
		SmallIconInput: "Small Icon (64x64)",
		SmallIconInputPH: "Small Icon Filename",
		MediumIconInput: "Medium Icon (128x128)",
		MediumIconInputPH: "Medium Icon Filename",
		LargeIconInput: "Large Icon (256x256)",
		LargeIconInputPH: "Large Icon Filename",

		GeneralTitle: "General",
		EquipableTab: "Equipable",
		EquipmentSlotInput: "Equipment Slot:",
		SlotUndefined: "Select...",
		MinLevelInput: "Min.Level:",
		MaxLevelInput: "Max.Level:",

		StatsTitle: "Stats",

		TagsTab: "Tags",
		KeysTitle: "Keys",
		ValuesTitle: "Values",
		AddTagBtn: "Add Tag",
		TagKeyInputPH: "Tag-Name",
		TagValueInputPH: "Tag-Value",

		Dagger: "Dagger",
		Sword: "Sword",
		GreatSword: "Great Sword",
		Fists: "Fists",
		Bow: "Bow",
		Wand: "Wand",
		Staff: "Staff",
		Dolls: "Dolls",
		Head: "Head",
		EaringLeft: "Left Earring",
		EaringRight: "Right Earring",
		Neck: "Neck",
		Shoulders: "Shoulders",
		Body: "Body",
		Hands: "Hands",
		RingLeft: "Left Ring",
		RingRight: "Right Earring",
		Belt: "Belt",
		Legs: "Legs",
		Shoes: "Shoes",

		"HP-abbr": "HP",
		"HP-full": "Health",
		"MP-abbr": "MP",
		"MP-full": "Mana",
		"SP-abbr": "SP",
		"SP-full": "Spirit",
		"STR-abbr": "STR",
		"STR-full": "Strength",
		"DEX-abbr": "DEX",
		"DEX-full": "Dexterity",
		"VIT-abbr": "VIT",
		"VIT-full": "Vitality",
		"CON-abbr": "CON",
		"CON-full": "Constitution",
		"EVA-abbr": "EVA",
		"EVA-full": "Evasion",
		"WIS-abbr": "WIS",
		"WIS-full": "Wisdom",
		"INT-abbr": "INT",
		"INT-full": "Intelligence",
		"MND-abbr": "MND",
		"MND-full": "Mind",
		"TRQ-abbr": "TRQ",
		"TRQ-full": "Tranquil",
		"BKR-abbr": "BKR",
		"BKR-full": "Bokor",

		MMTitle: "Main Menu",
		MMCurrentProject: "Current Project: ",
		MMEditorBtn: "Editor",
		MMSimulatorBtn: "Simulator",
		MMTestPlayerBtn: "Test Player",
		MMProjectMenu: "Project Manager",
		MMProjectViewerBtn: "Project Viewer",
		MMComponentEditorBtn: "Component Editor",

		CEDNavTitle: "Component Editor",
		CEDNewComponent: "New Component",
		CEDLoadComponent: "Load Component",
		CEDAddParam: "Add Parameter",

		CEDCompNamePH: "Component Name",
		CEDParamTitle: "Parameters",
		CEDAddParam: "Add Parameter",
		CEDParamNamePH: "Parameter Name",
		CEDTypeText: "Text",
		CEDTypeNumber: "Number",
		CEDTypeDropdown: "DropDown",
		CEDTypeColor: "Color",
		CEDTypeList: "List",
		CEDRequired: "Required",
		CEDRegex: "RegEx",

		ProjMenuTitle: "Projects",
		ProjListBtn: "Projects",
		ProjAPIMapping: "REST end-point mapping",
		ManageMembers: "Manage Members",
		ProjInviteMembers: "Invite Members",

		ProjNameTTitle: "Name",
		ProjCreateDateTTitle: "Created",
		ProjLastDateTTitle: "Last Edited",
		ProjStatusTitle: "Status",
		ProjStatusInactive: "Inactive",
		ProjectUndefined: "No Project Loaded",

		DateTimeUndefined: "--/--/---- --:--:--",
		NewProjName: "New Project",
		ProjModalOK: "OK",
		ProjModalCancel: "Cancel",
		ProjModalApply: "Apply",
		ProjModalLoad: "Load Project",
		ProjModalUnload: "Unload Project",
		ProjMIDLabel: "Project ID:",
		ProjMNameLabel: "Project Name:",
		ProjMCreateDate: "Created:",
		ProjMLastEdit: "Date Modified:",

		LoadingTitleGeneric: "Please wait",
		LoadingTextGeneric: "Loading...",

		BtnCancel: "Cancel"
	},
	zh: true,
	ja: true,
	ko: true,
	id: true
});