define({
	root: {
		About: "by Dan Cuccia",
		OK: "OK",
		Yes: "Yes",
		No: "No",
		Cancel: "Cancel",
		AreYouSure: "Are you sure?",
		SaveCurrent: "Save current changes?",
		SaveError: "An Error has occured attempting to save, review your content for any errors, and please try again.",
		EquipSlotUndefined: "Equipment Slot must be assigned",
		ConnectConditionUndefined: "Connection Condition must be defined",
		ConnectZeroQuantity: "Quantity requirement of Zero?",
		ConnectMaxQuantity: "Quantity requirement must be less than 1000",
		ConnectTargetUndefined: "Connection Target has not been defined",
		IDUndefined: "ID must be defined",
		DuplicateID: "Duplicate ID found",
		DuplicateName: "Duplicate Name found",
		NameUndefined: "Name must be defined",
		KeyUndefined: "Key must be defined",
		LabelUndefined: "Label must be defined",
		DescriptionUndefined: "Description is undefined",
		SmallIconUndefined: "Small Icon file is undefined",
		MediumIconUndefined: "Medium Icon file is undefined",
		LargeIconUndefined: "Large Icon file is undefined",
		TagKeyUndefined: "Tag must have key defined",
		TagValueUndefined: "Tag must have value defined",
		TagKeyDuplicate: "Duplicate Key found",
		MMLoadProjectTitle: "No Project Loaded!",
		MMLoadProject: "Load a project, or create a new one inside the Project Manager to start."
	},
	zh: true,
	ja: true,
	ko: true,
	id: true
});