define({
	"Title": "이름",
	"MBFile": "파일",
	"MBNewProj": "새 프로젝트",
	"MBLoadProj": "로드 프로젝트",
	"MBSave": "저장",
	"MBSaveAs": "다른 이름으로 저장 ...",
	"MBExport": "수출",
	"MBExportCGEN": ".cgen",
	"MBExportXML": ".xml",
	"MBExportJSON": ".json",
	"MBQuit": "종료",

	"MBEdit": "편집",
	"MBCreate": "만들기",
	"MBEmptyObj": "빈 객체",
	"MBKeyItem": "주요 항목",
	"MBConsumable": "소모품",
	"MBArmor": "갑옷",
	"MBWeapon": "무기",

	"MBHelp": "도와주세요",
	"MBAbout": "약",
	"MBSearchInputPH": "이름이나 식별 로 검색",


	"Components": "구성 요소들",
	"ErrorsTitle": "오류 :",
	"WarningsTitle": "경고 :",

	"GeneralTab": "일반",
	"IDTitle": "신분증",
	"IDInput": "신분증",
	"IDInputPH": "고유 식별",
	"NameInput": "이름",
	"NameInputPH": "고유 이름",
	"DescriptionInput": "기술",
	"DescInputPH": "상세 설명",
	"ConnectionsTitle": "연결",
	"CreateConnection": "새 연결 만들기",
	"ConnectUndefined": "선택 ...",
	"ConnectRequires": "필요",
	"ConnectConsumes": "소비된다",
	"TargetSelectBtn": "선택합니다",

	"RenderableTab": "렌더",
	"IconsTitle": "아이콘",
	"SmallIconInput": "작은 아이콘 (64x64)",
	"SmallIconInputPH": "작은 아이콘 파일 이름",
	"MediumIconInput": "중간 아이콘 (128x128)",
	"MediumIconInputPH": "중간 아이콘 파일 이름",
	"LargeIconInput": "큰 아이콘 (256x256)",
	"LargeIconInputPH": "큰 아이콘 파일 이름",

	"GeneralTitle": "일반",
	"EquipableTab": "장비",
	"EquipmentSlotInput": "장비 슬롯 :",
	"SlotUndefined": "선택 ...",
	"MinLevelInput": "최소 수준",
	"MaxLevelInput": "최대 레벨",

	"StatsTitle": "통계",

	"TagsTab": "태그",
	"KeysTitle": "키",
	"ValuesTitle": "값",
	"AddTagBtn": "태그 추가",
	"TagKeyInputPH": "태그 이름",
	"TagValueInputPH": "태그 값",

	"Dagger": "단검",
	"Sword": "검",
	"GreatSword": "대검",
	"Fists": "주먹",
	"Bow": "활",
	"Wand": "지팡이",
	"Staff": "직원",
	"Dolls": "인형",
	"Head": "머리",
	"EaringLeft": "왼쪽 귀걸이",
	"EaringRight": "오른쪽 귀걸이",
	"Neck": "목",
	"Shoulders": "어깨",
	"Body": "몸",
	"Hands": "손",
	"RingLeft": "왼쪽 반지",
	"RingRight": "오른쪽 반지",
	"Belt": "벨트",
	"Legs": "다리",
	"Shoes": "구두",

	"HP-abbr": "HP",
	"HP-full": "건강",
	"MP-abbr": "MP",
	"MP-full": "마법",
	"SP-abbr": "SP",
	"SP-full": "정신",
	"STR-abbr": "STR",
	"STR-full": "힘",
	"DEX-abbr": "DEX",
	"DEX-full": "재치",
	"VIT-abbr": "VIT",
	"VIT-full": "활력",
	"CON-abbr": "CON",
	"CON-full": "헌법",
	"EVA-abbr": "EVA",
	"EVA-full": "회피",
	"WIS-abbr": "WIS",
	"WIS-full": "지혜",
	"INT-abbr": "INT",
	"INT-full": "지성",
	"MND-abbr": "MND",
	"MND-full": "마음",
	"TRQ-abbr": "TRQ",
	"TRQ-full": "조용한",
	"BKR-abbr": "BKR",
	"BKR-full": "부두교",

	"MMTitle": "메인 메뉴",
	"MMEditorBtn": "편집자",
	"MMSimulatorBtn": "시뮬레이터",
	"MMTestPlayerBtn": "테스트 플레이어",
	"MMProjectViewerBtn": "프로젝트 뷰어",
	"MMComponentEditorBtn": "구성 요소 편집기"
});