define({
	"About": "로 Dan Cuccia",
	"OK": "좋아요",
	"Yes": "예",
	"No": "예",
	"Cancel": "취소",
	"AreYouSure": "확실 해요 ?",
	"SaveCurrent": "현재 변경 사항을 저장 ?",
	"SaveError": "오류가 , 저장 오류 에 대한 귀하의 콘텐츠를 검토하고 다시 시도하십시오 시도 발생했습니다 .",
	"EquipSlotUndefined": "장비 슬롯 이 할당되어야합니다",
	"ConnectConditionUndefined": "연결 상태 를 정의해야합니다",
	"ConnectZeroQuantity": "이해가되지 않습니다 제로 의 수량 요건",
	"ConnectMaxQuantity": "수량 요구 사항은 1000 이하 여야합니다",
	"ConnectTargetUndefined": "접속 상대 가 정의되지 않았다",
	"IDUndefined": "식별 정의해야합니다",
	"DuplicateID": "중복 ID 를 찾을 수",
	"DuplicateName": "이름 이 중복 된",
	"NameUndefined": "이름 이 정의되어야합니다",
	"DescriptionUndefined": "설명 은 정의되지 않습니다",
	"SmallIconUndefined": "작은 아이콘 파일 은 정의되지 않습니다",
	"MediumIconUndefined": "중간 아이콘 파일 은 정의되지 않습니다",
	"LargeIconUndefined": "큰 아이콘 파일 은 정의되지 않습니다",
	"TagKeyUndefined": "태그 키를 정의해야합니다",
	"TagValueUndefined": "태그 값을 정의해야합니다",
	"TagKeyDuplicate": "중복 키 를 찾을 수"
});